Repository cloudfoundry-incubator/eirini, pull requests merged in 2019-08, with the labels that each got.

#69 Fix unregister routes on pod deletion
  k8s/informers/route/instance_informer.go
  k8s/informers/route/instance_informer_test.go
  k8s/informers/route/uri_informer.go
  k8s/informers/route/uri_informer_test.go
Labels: scheduled

#70 fix the missing env vars for staging
  k8s/desiretask.go
  k8s/desiretask_test.go
  k8s/statefulset.go
  k8s/statefulset_test.go
  models.go
Labels: unscheduled

#67 Allow RTR messages to appear in cf logs stream
  k8s/informers/route/instance_informer_test.go
  k8s/informers/route/uri_informer.go
  k8s/informers/route/uri_informer_test.go
  k8s/route_collector.go
  k8s/route_collector_test.go
Labels: in progress
